service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    iam:
      role:
        statements: # permissions for all of your functions can be set here
          - Effect: Allow
            Action: # Gives permission to DynamoDB tables in a specific region
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource: 'arn:aws:dynamodb:us-east-1:*:*'
plugins:
  - ./vendor/bref/bref
  - serverless-lift
functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            -   httpApi: '*'

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'

constructs:
  website:
    type: server-side-website
    assets:
      '/js/*': public/js
      '/css/*': public/css
      '/images/*': public/images
      '/theme/*': public/theme
